name: Deploy VitePress site to Pages

on:
  # Runs on pushes targeting the `main` branch. Change this to `master` if you're
  # using the `master` branch as the default branch.
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  # needed for the anonymous submission page
  contents: write
  #contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

defaults:
  run:
    working-directory: ./demo

jobs:
  # Build job
  build:
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: demo/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build with VitePress
        run: npm run docs:build
      # Remove the section after making the repo public
      - name: Commit the version for reviewers
        run: |
          rm -rf ../review-demo
          mkdir -p ../review-demo
          cp -r .vitepress/dist/* ../review-demo/
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add ../review-demo
          git diff --cached --quiet || git commit -m "Add a folder with the built demo for anonymised GH pages"
          git push
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./demo/.vitepress/dist

  # Uncomment when the repo is public
  # Deployment job
  # deploy:
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   needs: build
  #   runs-on: ubuntu-latest
  #   name: Deploy
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v4